name: Validate and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Validate JSON files
      run: npm run validate
      
    - name: Run tests
      run: npm test
      
    - name: Check for secrets
      run: |
        if grep -r "sk-" workflows/ || grep -r "password" workflows/; then
          echo "Found potential secrets in workflows!"
          exit 1
        fi
